# Tests, builds, and releases a plugin and documentation.
# See https://git.luminfire.net/ops/tooling/ci/gitlab-ci-general/-/tree/master/wp-plugin

stages:
  - test
  - build
  - deploy


include:
  - project: 'ops/tooling/ci/gitlab-ci-templates'
    file:
      - 'test/php-syntax-check.yml'

# Test PHPUnit:
#   stage: test
#   tags:
#     - docker
#   image: gitlab/dind:latest
#   services:
#     - docker:dind
#   script:
#     - docker run --rm --privileged -v "$(pwd):/code" humanmade/plugin-tester --stop-on-error

Build Plugin Package:
  stage: build
  resource_group: build_plugin
  only:
    - tags
  script:
    - wp dist-archive . $PLUGIN_SLUG.$CI_COMMIT_TAG.zip
  artifacts:
    name: "$PLUGIN_SLUG.$CI_COMMIT_TAG"
    paths:
      - $PLUGIN_SLUG.$CI_COMMIT_TAG.zip

Deploy Documentation:
  stage: deploy
  only:
    - master
  resource_group: docs
  environment:
    name: docs
    url: $DOCS_URL
  cache:
    policy: pull
  script:
    - curl $DEPLOY_DOCS
