# Tests, builds, and releases a plugin and documentation.
# See https://git.luminfire.net/ops/tooling/ci/gitlab-ci-general/-/tree/master/wp-plugin

stages:
  - test
  - build
  - deploy


include:
  - project: 'templates/gitlab/ci-templates'
    file:
      - 'presets/php.yml'
      - 'build/wp-plugin.yml'
      - 'deploy/documentation/brilliantsolutions-docsify.yml'
