# Tests, builds, and releases a plugin and documentation.
# See https://git.luminfire.net/ops/tooling/ci/gitlab-ci-general/-/tree/master/wp-plugin

stages:
  - solcare
  - test
  - build
  - deploy
  - release

variables:
  PLUGIN_SLUG: field-helpe-for-gravity-forms
  CLOUDFLARE_PAGES_PROJECT_NAME: field-helper-for-gravity-forms
  # CLOUDFLARE_API_TOKEN: # add to GitLab CI/CD variable
  PHP_VERSION: "7.4"

include:
  - project: "templates/gitlab/ci-templates"
    file:
      - "presets/php.yml"
      - "test/phpcs.yml"
      - "test/phpstan.yml"
      - "build/wp-plugin.yml"
      - "deploy/documentation/brilliantsolutions-cloudflare-pages.yml"
