stages:
  - test
  - build
  - deploy

Test Changed Files:
  stage: test
  environment:
    name: php-test-syntax-diff
  script:
    - bin/php-syntaxChecker-changed.sh

Test All Files:
  stage: test
  environment:
    name: php-test-syntax-all
  only:
    - merge_requests
  script:
    - bin/php-syntaxChecker-full.sh

Build Plugin Package:
  stage: build
  only:
    - tags
  script:
    - wp dist-archive . $PLUGIN_SLUG.$CI_COMMIT_TAG.zip
  artifacts:
    name: "$PLUGIN_SLUG.$CI_COMMIT_TAG"
    paths:
      - $PLUGIN_SLUG.$CI_COMMIT_TAG.zip
  when: manual

Deploy Documentation:
  stage: deploy
  only:
    - master
  environment:
    name: docs
    url: $DOCS_URL
  script:
    - curl $DEPLOY_DOCS
