# Tests, builds, and releases a plugin and documentation.
# See https://git.luminfire.net/ops/tooling/ci/gitlab-ci-general/-/tree/master/wp-plugin

stages:
  - test
  - build
  - deploy


include:
  - project: 'templates/gitlab/ci-templates'
    file:
      - 'test/php-syntax-check.yml'
      - 'deploy/documentation/brilliantsolutions-docsify.yml'

# Note: this is basically the same as https://git.luminfire.net/templates/gitlab/ci-templates/-/blob/master/build/wp-plugin.yml but without S3 as this is deployed to wordpress.org plugin repository.
build:release-package:
  stage: build
  resource_group: build_plugin
  only:
    - tags
  script:
    - wp dist-archive . $PLUGIN_SLUG.$CI_COMMIT_TAG.zip
  artifacts:
    name: "$PLUGIN_SLUG.$CI_COMMIT_TAG"
    paths:
      - $PLUGIN_SLUG.$CI_COMMIT_TAG.zip
