# Tests, builds, and releases a plugin and documentation.
# See https://git.luminfire.net/ops/tooling/ci/gitlab-ci-general/-/tree/master/wp-plugin

stages:
  - test
  - build
  - deploy

# Run syntax checker
Test Syntax:
  tags:
    - docker
  image: git.luminfire.net:5005/ops/tooling/ci/gitlab-runner-tooling/gitlab-docker-runners/syntax-checker
  services:
    - docker:dind
  stage: test
  script:
    - phplint

# Test PHPUnit:
#   stage: test
#   tags:
#     - docker
#   image: gitlab/dind:latest
#   services:
#     - docker:dind
#   script:
#     - docker run --rm --privileged -v "$(pwd):/code" humanmade/plugin-tester --stop-on-error

Build Plugin Package:
  stage: build
  only:
    - tags
  script:
    - wp dist-archive . $PLUGIN_SLUG.$CI_COMMIT_TAG.zip
  artifacts:
    name: "$PLUGIN_SLUG.$CI_COMMIT_TAG"
    paths:
      - $PLUGIN_SLUG.$CI_COMMIT_TAG.zip
  when: manual

Deploy Documentation:
  stage: deploy
  only:
    - master
  environment:
    name: docs
    url: $DOCS_URL
  cache:
    policy: pull
  script:
    - curl $DEPLOY_DOCS
