# Tests, builds, and releases a plugin and documentation.
# See https://git.luminfire.net/ops/tooling/ci/gitlab-ci-general/-/tree/master/wp-plugin

stages:
  - solcare
  - test
  - build
  - deploy
  - release

include:
  - project: 'templates/gitlab/ci-templates'
    file:
      - 'presets/php.yml'
      - 'test/phpcs.yml'
      - 'test/phpstan.yml'
      - 'build/wp-plugin.yml'
      - 'deploy/documentation/brilliantsolutions-docsify.yml'

test:phpstan:
  image: git.luminfire.net:5005/luminfire/ops/devops/docker/stacks/edbizarro-gitlab-ci-pipeline-php:7.4-fpm
