# Tests, builds, and releases a plugin and documentation.
# See https://git.luminfire.net/ops/tooling/ci/gitlab-ci-general/-/tree/master/wp-plugin

stages:
  - test
  - build
  - deploy


include:
  - project: 'ops/tooling/ci/gitlab-ci-templates'
    file:
      - 'test/php-syntax-check.yml'
      - 'deploy/documentation/brilliantsolutions-docsify.yml'

# Test PHPUnit:
#   stage: test
#   tags:
#     - docker
#   image: gitlab/dind:latest
#   services:
#     - docker:dind
#   script:
#     - docker run --rm --privileged -v "$(pwd):/code" humanmade/plugin-tester --stop-on-error

# Note: this is basically the same as https://git.luminfire.net/ops/tooling/ci/gitlab-ci-templates/-/blob/master/build/wp-plugin.yml but without S3 as this is deployed to wordpress.org plugin repository.
Build Plugin Package:
  stage: build
  resource_group: build_plugin
  only:
    - tags
  script:
    - wp dist-archive . $PLUGIN_SLUG.$CI_COMMIT_TAG.zip
  artifacts:
    name: "$PLUGIN_SLUG.$CI_COMMIT_TAG"
    paths:
      - $PLUGIN_SLUG.$CI_COMMIT_TAG.zip
